### ISSUE TITLE
Interface between VM and Mijit

### ISSUE THREAD

**Issue by rrthomas** [apt1002/mijit#1]
1. Format of specification. (Represent state and transitions.)
2. Format of output: some C source that can be pasted into a `run` function (or *is* a function), or an object file with a defined entry point.

**Comment by apt1002** [comment]
For 2, I think Mijit should provide a C-callable interface written in Rust something like this:

```
type VmError = usize;
type TrapHandler = extern fn(VmState) -> VmError;
extern fn mijit_new(usize) -> Option<JitCache>;
extern fn mijit_drop(JitCache);
extern fn mijit_run(&mut JitCache, &mut VmState, TrapHandler) -> VmError;
```

**Comment by apt1002** [comment]
1 is more difficult.

Almost certainly some VM-specific Rust code will be required, e.g. to define the arithmetic primitives and the memory model. Mijit can provide a toolkit of commonly needed things, e.g. a stack, some registers, and 32- and 64-bit integer arithmetic primitives, but it should not aim to be exhaustive, because it will not succeed, and because third-party libraries can fill the gaps better.

The VM spec itself will mostly be data, but will probably need to include some slightly opaque callbacks written in Rust, e.g. for assembling arithmetic or memory primitives (for now, lets not worry too much about what target we're assembling for, and just assume x64_64; I don't anticipate porting to be a difficult problem). There may well be some VM-specific wrapper code written in Rust to interface with C, e.g. the TrapHandler.

The VM spec could be a data structure, but it could also be a trait implementation. Modelling it as data is more flexible, but modelling it as code removes a level of interpretation from Mijit's code generator. We should probably try the easier option (a data structure) first, and change to a trait implementation later as an optimization.

So I expect there will be a Rust crate called e.g. `mijit_beetle` that depends on `mijit`. The spec can be constructed in `mijit_beetle` manually, or by auto-generating a Rust source file, or by parsing a YAML file, or whatever. The `beetle` binary can use the C interface exported by `mijit_beetle`, possible via a C library `libbeetle`. At first, it might be easier to blur the boundary between `mijit` and `mijit_beetle`, and factor out the latter later, e.g. at the same time as writing `mijit_mit`.

How does that sound?

**Comment by apt1002** [comment]
We've made a bit of progress on "1. Format of specification". Currently, the VM spec is a trait implementation. We have implemented one example VM: [Beetle](https://github.com/rrthomas/beetle).

The trait provides the type of addresses that can be used in Load and Store actions. These include the VM registers. We will need a way of lowering these to actual memory addresses. We will also need a way of caching the values of these locations in real registers.

The trait provides the type of a state of the VM control-flow state machine. For each state, it provides a data structure giving a list of cases, each consisting of a test, a list of actions, and a new state. Mijit defines the representation of the tests and actions for now.

**Comment by apt1002** [comment]
I think this question has cleared up over time. The design is still in flux, but the broad strokes are in place, so I'm going to summarise the progress and close the issue.

We have invented a domain-specific language (in mod `code`) for specifying the VM. It is low-level (roughly assembly language). It restricts the VM to a finite number of storage locations and a finite number of control-flow states. Anything more complicated than that has to be expressed using virtual code. The language has three main components:

 - A branch-free instruction set (`code::Action`) for expressing arithmetic, memory access, and data flow.
 - A tractable and side-effect free instruction set (`code::TestOp`) for expressing control-flow tests.
 - A way of defining a finite-state machine (trait `code::Machine`).

We have used this language to implement (most of) [Beetle](https://github.com/rrthomas/beetle). We have also written a tiny test machine that just computes factorials (and does not execute any virtual code). These could be useful in future as worked examples of how to use Mijit. The Beetle implementation should probably become a separate project that depends on Mijit, but while Mijit's design is in flux it is convenient to have it as a submodule `beetle`.

So far, we have not attempted anything that requires Mijit to call Rust code. We have a few ideas for how this might work. Probably the most efficient would be to add to the domain-specific language the ability to call functions using a subset of the C calling convention. The function would receive 64-bit arguments from Mijit, and would return an error code. Mijit would then test the error code, and pass it on if it's non-zero. This would be sufficient to implement the TrapHandler idea. It could also be used to implement accelerators, I/O primitives, and other rarely-used functionality that Mijit doesn't need to understand.

Given any implementation of `code::Machine`, we can construct (at run time) a `Jit`, which represents a translation of the specification into native machine code. Eventually this will profile, specialize and optimize itself, but for now it is a naive interpreter. It exposes a generic (Rust) API, parameterized on the `Machine`. The API is good enough for reading and writing the machine's registers, and for calling the machine from Rust.

While writing tests for Beetle, we have started writing a Beetle-specific (Rust) API in terms of the generic API. This handles things like allocating Beetle's memory and initializing its stacks. It can call Beetle subroutines from Rust using Beetle's calling convention. It provides higher-level primitives for manipulating Beetle's state, e.g. pushing and popping values to/from its stacks. It seems likely that most virtual machines will have something similar. This is the API that will get C bindings.
