### ISSUE TITLE
Simplify `beetle::Machine::get_code()`.

### ISSUE THREAD

**Issue by apt1002** [apt1002/mijit#5]
The `get_code()` method of `beetle::Machine` has unnecessary complexity in a number of ways:

- [ ] The code for `Lshift` and `Rshift` differs only in one `BinaryOp`.

- [x] The following code sequence is common, and could be abbreviated:
    ```
    b.load_global(<reg>, <global>);
    b.const_binary(<op>, <reg>, <reg>, <constant>);
    b.store_global(<reg>, <global>);
    ```
    Usually, `<op>` is `Add` and `<constant>` is `cell_bytes(<int>)`.

- [ ] The following code sequence is common, and could be abbreviated:
    ```
    b.const_binary(Add, <reg>, <value>, cell_bytes(<n>));
    b.load(RD, <reg>);
    ```

- [ ] Code to increment `B_EP` and jump to `Root` is common. It occurs in: `Qbranch`, `Loop`.

- [ ] The code for `Ploopp` and `Ploopm` appears to be identical.

- [ ] The code for `Ploopip` and `Ploopim` appears to be identical.

- [ ] The code for `Ploop` and `Ploopi` differs only in the `State`s they jump to.

- [ ] The difference between instructions and their `i` variant are very small and could be parametrized. This occurs in: `Qbranch`, `Loop`, `Ploop`.

- [ ] The difference between `0`, `1`, `-1`, `CELL` and `-CELL` could be parametrized.

- [ ] The difference between the various unary operators could be parametrized.

- [ ] The difference between the various binary operators could be parametrized.

- [ ] The difference between the various `item op constant` operators could be parametrized.

- [ ] The difference between the various `constant op item` operators could be parametrized.

- [ ] The difference between the various `<reg>@` operators could be parametrized.

- [ ] The difference between the various `<reg>!` operators could be parametrized.

**Comment by rrthomas** [comment]
I note that in the C implementation of Beetle, many of the above comments also apply, but it would barely be worth factoring out the commonality as the code is short half a dozen lines or fewer in most cases) and the extra abstraction would arguably make it harder to read. The Mijit code, unsurprisingly, is much longer, because it's effectively written in abstract assembler, not C.

It's interesting to notice therefore, that all the proposed abstractions above keep the low level of abstraction of the "abstract assembler" (and that they're mostly applicable to the C too, as mentioned above) rather than trying to raise the level of abstraction of the abstract assembler (effectively writing a Beetle-specific DSL).

**Comment by apt1002** [comment]
@NickBarnes remarked that if Mijit ever becomes popular, people will inevitably generate Mijit code by compiling other languages. I don't think there's anything wrong with that.

**Comment by apt1002** [comment]
Moved to [beetle-mijit](https://github.com/rrthomas/beetle-mijit/issues/1).
